const countryList = {
  AED: { country: "United Arab Emirates", code: "AE", currency: "UAE Dirham" },
  AFN: { country: "Afghanistan", code: "AF", currency: "Afghan Afghani" },
  XCD: {
    country: "Antigua and Barbuda",
    code: "AG",
    currency: "East Caribbean Dollar",
  },
  ALL: { country: "Albania", code: "AL", currency: "Albanian Lek" },
  AMD: { country: "Armenia", code: "AM", currency: "Armenian Dram" },
  ANG: {
    country: "Netherlands Antilles",
    code: "AN",
    currency: "Netherlands Antillean Guilder",
  },
  AOA: { country: "Angola", code: "AO", currency: "Angolan Kwanza" },
  AQD: { country: "Antarctica", code: "AQ", currency: "Antarctican Dollar" },
  ARS: { country: "Argentina", code: "AR", currency: "Argentine Peso" },
  AUD: { country: "Australia", code: "AU", currency: "Australian Dollar" },
  AZN: { country: "Azerbaijan", code: "AZ", currency: "Azerbaijani Manat" },
  BAM: {
    country: "Bosnia and Herzegovina",
    code: "BA",
    currency: "Bosnia-Herzegovina Convertible Mark",
  },
  BBD: { country: "Barbados", code: "BB", currency: "Barbadian Dollar" },
  BDT: { country: "Bangladesh", code: "BD", currency: "Bangladeshi Taka" },
  XOF: { country: "Benin", code: "BE", currency: "West African CFA Franc" },
  BGN: { country: "Bulgaria", code: "BG", currency: "Bulgarian Lev" },
  BHD: { country: "Bahrain", code: "BH", currency: "Bahraini Dinar" },
  BIF: { country: "Burundi", code: "BI", currency: "Burundian Franc" },
  BMD: { country: "Bermuda", code: "BM", currency: "Bermudian Dollar" },
  BND: { country: "Brunei Darussalam", code: "BN", currency: "Brunei Dollar" },
  BOB: { country: "Bolivia", code: "BO", currency: "Bolivian Boliviano" },
  BRL: { country: "Brazil", code: "BR", currency: "Brazilian Real" },
  BSD: { country: "Bahamas", code: "BS", currency: "Bahamian Dollar" },
  NOK: { country: "Bouvet Island", code: "BV", currency: "Norwegian Krone" },
  BWP: { country: "Botswana", code: "BW", currency: "Botswana Pula" },
  BYR: { country: "Belarus", code: "BY", currency: "Belarusian Ruble" },
  BZD: { country: "Belize", code: "BZ", currency: "Belize Dollar" },
  CAD: { country: "Canada", code: "CA", currency: "Canadian Dollar" },
  CDF: {
    country: "Democratic Republic of the Congo",
    code: "CD",
    currency: "Congolese Franc",
  },
  XAF: {
    country: "Central African Republic",
    code: "CF",
    currency: "Central African CFA Franc",
  },
  CHF: { country: "Switzerland", code: "CH", currency: "Swiss Franc" },
  CLP: { country: "Chile", code: "CL", currency: "Chilean Peso" },
  CNY: { country: "China", code: "CN", currency: "Chinese Yuan" },
  COP: { country: "Colombia", code: "CO", currency: "Colombian Peso" },
  CRC: { country: "Costa Rica", code: "CR", currency: "Costa Rican Colón" },
  CUP: { country: "Cuba", code: "CU", currency: "Cuban Peso" },
  CVE: { country: "Cape Verde", code: "CV", currency: "Cape Verdean Escudo" },
  CYP: { country: "Cyprus", code: "CY", currency: "Cypriot Pound" },
  CZK: { country: "Czech Republic", code: "CZ", currency: "Czech Koruna" },
  DJF: { country: "Djibouti", code: "DJ", currency: "Djiboutian Franc" },
  DKK: { country: "Denmark", code: "DK", currency: "Danish Krone" },
  DOP: {
    country: "Dominican Republic",
    code: "DO",
    currency: "Dominican Peso",
  },
  DZD: { country: "Algeria", code: "DZ", currency: "Algerian Dinar" },
  ECS: { country: "Ecuador", code: "EC", currency: "Ecuadorian Sucre" },
  EEK: { country: "Estonia", code: "EE", currency: "Estonian Kroon" },
  EGP: { country: "Egypt", code: "EG", currency: "Egyptian Pound" },
  ETB: { country: "Ethiopia", code: "ET", currency: "Ethiopian Birr" },
  EUR: {
    country: "Many countries, including France",
    code: "FR",
    currency: "Euro",
  },
  FJD: { country: "Fiji", code: "FJ", currency: "Fijian Dollar" },
  FKP: {
    country: "Falkland Islands",
    code: "FK",
    currency: "Falkland Islands Pound",
  },
  GBP: {
    country: "United Kingdom",
    code: "GB",
    currency: "British Pound Sterling",
  },
  GEL: { country: "Georgia", code: "GE", currency: "Georgian Lari" },
  GGP: { country: "Guernsey", code: "GG", currency: "Guernsey Pound" },
  GHS: { country: "Ghana", code: "GH", currency: "Ghanaian Cedi" },
  GIP: { country: "Gibraltar", code: "GI", currency: "Gibraltar Pound" },
  GMD: { country: "Gambia", code: "GM", currency: "Gambian Dalasi" },
  GNF: { country: "Guinea", code: "GN", currency: "Guinean Franc" },
  GTQ: { country: "Guatemala", code: "GT", currency: "Guatemalan Quetzal" },
  GYD: { country: "Guyana", code: "GY", currency: "Guyanese Dollar" },
  HKD: { country: "Hong Kong", code: "HK", currency: "Hong Kong Dollar" },
  HNL: { country: "Honduras", code: "HN", currency: "Honduran Lempira" },
  HRK: { country: "Croatia", code: "HR", currency: "Croatian Kuna" },
  HTG: { country: "Haiti", code: "HT", currency: "Haitian Gourde" },
  HUF: { country: "Hungary", code: "HU", currency: "Hungarian Forint" },
  IDR: { country: "Indonesia", code: "ID", currency: "Indonesian Rupiah" },
  ILS: { country: "Israel", code: "IL", currency: "Israeli Shekel" },
  INR: { country: "India", code: "IN", currency: "Indian Rupee" },
  IQD: { country: "Iraq", code: "IQ", currency: "Iraqi Dinar" },
  IRR: { country: "Iran", code: "IR", currency: "Iranian Rial" },
  ISK: { country: "Iceland", code: "IS", currency: "Icelandic Króna" },
  JMD: { country: "Jamaica", code: "JM", currency: "Jamaican Dollar" },
  JOD: { country: "Jordan", code: "JO", currency: "Jordanian Dinar" },
  JPY: { country: "Japan", code: "JP", currency: "Japanese Yen" },
  KES: { country: "Kenya", code: "KE", currency: "Kenyan Shilling" },
  KGS: { country: "Kyrgyzstan", code: "KG", currency: "Kyrgyzstani Som" },
  KHR: { country: "Cambodia", code: "KH", currency: "Cambodian Riel" },
  KMF: { country: "Comoros", code: "KM", currency: "Comorian Franc" },
  KPW: { country: "North Korea", code: "KP", currency: "North Korean Won" },
  KRW: { country: "South Korea", code: "KR", currency: "South Korean Won" },
  KWD: { country: "Kuwait", code: "KW", currency: "Kuwaiti Dinar" },
  KYD: {
    country: "Cayman Islands",
    code: "KY",
    currency: "Cayman Islands Dollar",
  },
  KZT: { country: "Kazakhstan", code: "KZ", currency: "Kazakhstani Tenge" },
  LAK: { country: "Laos", code: "LA", currency: "Lao Kip" },
  LBP: { country: "Lebanon", code: "LB", currency: "Lebanese Pound" },
  LKR: { country: "Sri Lanka", code: "LK", currency: "Sri Lankan Rupee" },
  LRD: { country: "Liberia", code: "LR", currency: "Liberian Dollar" },
  LSL: { country: "Lesotho", code: "LS", currency: "Lesotho Loti" },
  LTL: { country: "Lithuania", code: "LT", currency: "Lithuanian Litas" },
  LVL: { country: "Latvia", code: "LV", currency: "Latvian Lats" },
  LYD: { country: "Libya", code: "LY", currency: "Libyan Dinar" },
  MAD: { country: "Morocco", code: "MA", currency: "Moroccan Dirham" },
  MDL: { country: "Moldova", code: "MD", currency: "Moldovan Leu" },
  MGA: { country: "Madagascar", code: "MG", currency: "Malagasy Ariary" },
  MKD: { country: "North Macedonia", code: "MK", currency: "Macedonian Denar" },
  MMK: { country: "Myanmar", code: "MM", currency: "Burmese Kyat" },
  MNT: { country: "Mongolia", code: "MN", currency: "Mongolian Tögrög" },
  MOP: { country: "Macau", code: "MO", currency: "Macanese Pataca" },
  MRO: { country: "Mauritania", code: "MR", currency: "Mauritanian Ouguiya" },
  MTL: { country: "Malta", code: "MT", currency: "Maltese Lira" },
  MUR: { country: "Mauritius", code: "MU", currency: "Mauritian Rupee" },
  MVR: { country: "Maldives", code: "MV", currency: "Maldivian Rufiyaa" },
  MWK: { country: "Malawi", code: "MW", currency: "Malawian Kwacha" },
  MXN: { country: "Mexico", code: "MX", currency: "Mexican Peso" },
  MYR: { country: "Malaysia", code: "MY", currency: "Malaysian Ringgit" },
  MZN: { country: "Mozambique", code: "MZ", currency: "Mozambican Metical" },
  NAD: { country: "Namibia", code: "NA", currency: "Namibian Dollar" },
  XPF: { country: "New Caledonia", code: "NC", currency: "CFP Franc" },
  NGN: { country: "Nigeria", code: "NG", currency: "Nigerian Naira" },
  NIO: { country: "Nicaragua", code: "NI", currency: "Nicaraguan Córdoba" },
  NPR: { country: "Nepal", code: "NP", currency: "Nepalese Rupee" },
  NZD: { country: "New Zealand", code: "NZ", currency: "New Zealand Dollar" },
  OMR: { country: "Oman", code: "OM", currency: "Omani Rial" },
  PAB: { country: "Panama", code: "PA", currency: "Panamanian Balboa" },
  PEN: { country: "Peru", code: "PE", currency: "Peruvian Sol" },
  PGK: {
    country: "Papua New Guinea",
    code: "PG",
    currency: "Papua New Guinean Kina",
  },
  PHP: { country: "Philippines", code: "PH", currency: "Philippine Peso" },
  PKR: { country: "Pakistan", code: "PK", currency: "Pakistani Rupee" },
  PLN: { country: "Poland", code: "PL", currency: "Polish Złoty" },
  PYG: { country: "Paraguay", code: "PY", currency: "Paraguayan Guaraní" },
  QAR: { country: "Qatar", code: "QA", currency: "Qatari Riyal" },
  RON: { country: "Romania", code: "RO", currency: "Romanian Leu" },
  RSD: { country: "Serbia", code: "RS", currency: "Serbian Dinar" },
  RUB: { country: "Russia", code: "RU", currency: "Russian Ruble" },
  RWF: { country: "Rwanda", code: "RW", currency: "Rwandan Franc" },
  SAR: { country: "Saudi Arabia", code: "SA", currency: "Saudi Riyal" },
  SBD: {
    country: "Solomon Islands",
    code: "SB",
    currency: "Solomon Islands Dollar",
  },
  SCR: { country: "Seychelles", code: "SC", currency: "Seychellois Rupee" },
  SDG: { country: "Sudan", code: "SD", currency: "Sudanese Pound" },
  SEK: { country: "Sweden", code: "SE", currency: "Swedish Krona" },
  SGD: { country: "Singapore", code: "SG", currency: "Singapore Dollar" },
  SKK: { country: "Slovakia", code: "SK", currency: "Slovak Koruna" },
  SLL: {
    country: "Sierra Leone",
    code: "SL",
    currency: "Sierra Leonean Leone",
  },
  SOS: { country: "Somalia", code: "SO", currency: "Somali Shilling" },
  SRD: { country: "Suriname", code: "SR", currency: "Surinamese Dollar" },
  STD: {
    country: "São Tomé and Príncipe",
    code: "ST",
    currency: "São Tomé and Príncipe Dobra",
  },
  SVC: { country: "El Salvador", code: "SV", currency: "Salvadoran Colón" },
  SYP: { country: "Syria", code: "SY", currency: "Syrian Pound" },
  SZL: { country: "Eswatini", code: "SZ", currency: "Swazi Lilangeni" },
  THB: { country: "Thailand", code: "TH", currency: "Thai Baht" },
  TJS: { country: "Tajikistan", code: "TJ", currency: "Tajikistani Somoni" },
  TMT: { country: "Turkmenistan", code: "TM", currency: "Turkmenistani Manat" },
  TND: { country: "Tunisia", code: "TN", currency: "Tunisian Dinar" },
  TOP: { country: "Tonga", code: "TO", currency: "Tongan Paʻanga" },
  TRY: { country: "Turkey", code: "TR", currency: "Turkish Lira" },
  TTD: {
    country: "Trinidad and Tobago",
    code: "TT",
    currency: "Trinidad and Tobago Dollar",
  },
  TWD: { country: "Taiwan", code: "TW", currency: "New Taiwan Dollar" },
  TZS: { country: "Tanzania", code: "TZ", currency: "Tanzanian Shilling" },
  UAH: { country: "Ukraine", code: "UA", currency: "Ukrainian Hryvnia" },
  UGX: { country: "Uganda", code: "UG", currency: "Ugandan Shilling" },
  USD: { country: "United States", code: "US", currency: "US Dollar" },
  UYU: { country: "Uruguay", code: "UY", currency: "Uruguayan Peso" },
  UZS: { country: "Uzbekistan", code: "UZ", currency: "Uzbekistani Soʻm" },
  VEF: { country: "Venezuela", code: "VE", currency: "Venezuelan Bolívar" },
  VND: { country: "Vietnam", code: "VN", currency: "Vietnamese Đồng" },
  VUV: { country: "Vanuatu", code: "VU", currency: "Vanuatu Vatu" },
  YER: { country: "Yemen", code: "YE", currency: "Yemeni Rial" },
  ZAR: { country: "South Africa", code: "ZA", currency: "South African Rand" },
  ZMK: { country: "Zambia", code: "ZM", currency: "Zambian Kwacha" },
  ZWD: { country: "Zimbabwe", code: "ZW", currency: "Zimbabwean Dollar" },
};
